### ISSUE TITLE
How can I get p values for all the positions?

### ISSUE THREAD

**Issue by bhargava-morampalli** [GoekeLab/xpore#125]
The default result is for most significant position in the RNA but is there an option which I can use to get the p-values for all the positions?

**Comment by yuukiiwa** [comment]
Hi @bhargava-morampalli,

If you use prefiltering like indicated below, then `xpore diffmod` only outputs the significants positions according to the threshold:
```
notes: Pairwise comparison without replicates with default parameter setting.

data:
    KO:
        rep1: ./data/HEK293T-METTL3-KO-rep1/dataprep
    WT:
        rep1: ./data/HEK293T-WT-rep1/dataprep    
    
out: ./out

method:
    prefiltering:
        method: t-test
        threshold: 0.1
```

If you want the `pval_<condition1>_vs_<condition2>` for all the positions, you will have to remove the prefiltering in `config.yml`, which is as follow:
```
notes: Pairwise comparison without replicates with default parameter setting.

data:
    KO:
        rep1: ./data/HEK293T-METTL3-KO-rep1/dataprep
    WT:
        rep1: ./data/HEK293T-WT-rep1/dataprep    
    
out: ./out
```
Thanks!

Best wishes,
Yuk Kei
