### ISSUE TITLE
Issue regarding the HEK293T data and preprocessed HEK293T data

### ISSUE THREAD

**Issue by daewon-gong** [GoekeLab/xpore#128]
Hello,

I noticed some issues while trying to run xpore on 3 replicates of the HEK293T-Mettl3-KO data and 3 replicates of the HEK293T-WT data downloaded from the provided ENA website using aspera.

1.  I get this gzip error while trying to untar `HEK293T-WT-rep2`, the `20190918_Sho_M3-2.tar.gz` file in HEK293T-KO-rep3: `gzip: 20190918_Sho_M3-2.tar.gz: invalid compressed data--crc error`. I tried re-downloading multiple times and still get the same errors.

2. Giving the preprocessed HEK293T data a try which were downloaded from zenodo. Running `xpore diffmod --config config_file` didn't give any errors but gave empty results with a`0 ids to be testing ...` message in the beginning.

Could someone check on these files for us. Thank you!

FYI: @jts

**Comment by yuukiiwa** [comment]
Hi @daewon-gong,

1. Do you mind sending us the md5sum of the file you downloaded, please? We can then check whether the file from ENA is the same the file on our side or it is corrupted.
2. Do you mind providing us the config.yml file so that we can see what the issue is.

Thank you!

Best wishes,
Yuk Kei

**Comment by daewon-gong** [comment]
Hi @yuukiiwa ,

1. Here are the md5sum of the files:

-  `38dbbb5c3531a627c57110ad8c3b628f  HEK293T-WT-rep2.tar.gz`
- `94231007837505fddfc374714e112847  HEK293T-Mettl3-KO-rep3.tar.gz`
- `3c85195505b5891752318580e41e28bc  20190918_Sho_M3-2.tar.gz` (This one is the file that seems corrupted in HEK293T-Mettl3-KO-rep3.tar.gz)

2. This is the config file I used:
```
data:
    KO:
        rep1: ./HEK293T_KO_rep1_pre/dataprep
        rep2: ./HEK293T_KO_rep2_pre/dataprep
        rep3: ./HEK293T_KO_rep3_pre/dataprep
    WT:
        rep1: ./HEK293T_WT_rep1_pre/dataprep
        rep2: ./HEK293T_WT_rep2_pre/dataprep
        rep3: ./HEK293T_WT_rep3_pre/dataprep

out: ./out
```

Thanks for the help!

Best,
Sean Gong
