### ISSUE TITLE
diffmod running problem

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/xpore#161]
Hi xPore team, (@yuukiiwa )
I have successfully run **xpore dataprep**, which generated all files namely, eventalign.index, data.json, data.index, data.readcount, data.log. I checked they contained data. Then, I prepared a YAML file as follows:
data:
    Diff:
        rep1: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/diff1
        rep2: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/diff2tr2
        rep3: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/diff3

    Undiff:
        rep1: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/undiff1
        rep2: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/undiff2
    
out: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep

method:
    prefiltering:
        method: t-test
        threshold: 0.1

Then, I submit a job that contain below command-

xpore diffmod --config nanocount_config.yml 

**However, after running for 24 hours I see the diffmod.tabl and diffmod.log are few bytes. diffmod.table is empty but diffmod.log file contains the list of many transcripts.**
Could you please help me fixing this problem?

I'll be very grateful to you.

Kind regards
Reza

**Comment by yuukiiwa** [comment]
Hi Reza (@rezarahman12),

You can try removing the prefiltering from your `nanocount_config.yml`, so it will look like the following:
```
data:
    Diff:
        rep1: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/diff1
        rep2: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/diff2tr2
        rep3: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/diff3

    Undiff:
        rep1: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/undiff1
        rep2: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/dataprep/undiff2

out: /scratch/project_mnt/S0077/xPore/rawdata/nanocount_data/diffmod
```

Another tip to speed up xpore diffmod is to add in the `--n_processes [number_of_cpus]` flag. Here is an example:
```
xpore diffmod --config nanocount_config.yml --n_processes 12
```

Thanks!

Best wishes,
Yuk Kei
