### ISSUE TITLE
Biological replicate

### ISSUE THREAD

**Issue by AndreaYCT** [GoekeLab/xpore#213]
Hi, 

xpore diffmod can calculate " Pairwise comparison without replicates with default parameter setting."

I'd like to maker sure that I can only have two input files. Is it possible to run with biological replicates (two samples for KO and two samples for WT)? 

 Thanks!

Andrea

**Comment by yuukiiwa** [comment]
Hi Andrea (tagging you here @AndreaYCT ),

You can add a second replicate like the following:

```
notes: Pairwise comparison without replicates with default parameter setting.

data:
    KO:
        rep1: ./data/HEK293T-METTL3-KO-rep1/dataprep
        rep2: ./data/HEK293T-METTL3-KO-rep2/dataprep
    WT:
        rep1: ./data/HEK293T-WT-rep1/dataprep
        rep2: ./data/HEK293T-WT-rep2/dataprep

out: ./out
```

Thanks!

Best wishes,
Yuk Kei

**Comment by AndreaYCT** [comment]
> Hi Andrea (tagging you here @AndreaYCT ),
> 
> You can add a second replicate like the following:
> 
> ```
> notes: Pairwise comparison without replicates with default parameter setting.
> 
> data:
>     KO:
>         rep1: ./data/HEK293T-METTL3-KO-rep1/dataprep
>         rep2: ./data/HEK293T-METTL3-KO-rep2/dataprep
>     WT:
>         rep1: ./data/HEK293T-WT-rep1/dataprep
>         rep2: ./data/HEK293T-WT-rep2/dataprep
> 
> out: ./out
> ```
> 
> Thanks!
> 
> Best wishes, Yuk Kei

Hi, @yuukiiwa,

In this case, I can have as many replicates as I wish, and I only can compare two exp groups, right?


Andrea

**Comment by yuukiiwa** [comment]
Hi Andrea (tagging you here @AndreaYCT),

You can have as many groups and replicates as you want as follows. Just that the more groups you include, the longer `xpore diffmod` will run due to the increasing number of pairwise comparisons.

```
data:
    groupA:
        rep1: ./data/A1/dataprep
        rep2: ./data/A2/dataprep
    groupB:
        rep1: ./data/B1/dataprep
        rep2: ./data/B2/dataprep
    groupC:
        rep1: ./data/C1/dataprep
        rep2: ./data/C2/dataprep
    groupD:
        rep1: ./data/D1/dataprep
        rep2: ./data/D2/dataprep

out: ./out
```

Thanks!

Best wishes,
Yuk Kei
